<?php

echo "<!-- \n";
echo "        Created by Zachary Hess for the CS2830 Final Project at the University of Missouri \n";
echo "-->\n";
echo "\n";
echo "<!-- \n";
echo "        Name: Zachary Hess\n";
echo "        Pawprint: zjhww8\n";
echo "        StudentID: 14263699\n";
echo "-->\n";
echo "\n";
echo "<!-- Main Page -->\n";
echo "\n";
echo "\n";
echo "<!DOCTYPE html>\n";
echo "\n";
echo "<html>\n";
echo "    <head>\n";
echo "        <title>Computers! Austin Terranova</title>\n";
echo "        <meta charset=\"utf-8\">\n";
echo "        <link rel=\"stylesheet\" type=\"text/css\" href=\"Styling.css\">\n";
echo "        <link href=\"https://fonts.googleapis.com/css?family=Acme\" rel=\"stylesheet\">\n";
echo "        <link href=\"https://fonts.googleapis.com/css?family=Ubuntu\" rel=\"stylesheet\">\n";
echo "        \n";
echo "    </head>\n";
echo "    \n";
echo "    <body>\n";
echo "        <header id=\"heading\">All About Computers!</header>\n";
echo "        \n";
echo "        <div id=\"columnZero\">\n";
echo "            <button class=\"headerButton\" onclick=\"loadPage('Home')\">Home</button>\n";
echo "        </div>\n";
echo "        \n";
echo "        <div id=\"columnOne\">\n";
echo "            <button class=\"headerButton\" onclick=\"loadPage('Parts')\">Parts</button>\n";
echo "        </div>\n";
echo "        \n";
echo "        <div id=\"columnTwo\">\n";
echo "            <button class=\"headerButton\" onclick=\"loadPage('Builds')\">Build</button>\n";
echo "        </div>\n";
echo "        \n";
echo "        <div id=\"columnThree\">\n";
echo "            <button class=\"headerButton\" onclick=\"loadPage('History')\">Feedback</button>\n";
echo "        </div>\n";
echo "        \n";
echo "        <img id=\"clipArtComputerRight\" src=\"/Photos/clipartComputer.png\" alt=\"Clipart Computer\">\n";
echo "        <img id=\"clipArtComputerLeft\" src=\"/Photos/clipartComputer.png\" alt=\"Clipart Computer\">\n";
echo "        \n";
echo "        <p id=\"instructionStuff\">On this website you can learn all about what parts make up a computer, how to build one, and the creation and evolution of the computer! <br><br> To get started simply click on either \"Parts\" \"Build\" or \"History\" above! <hr></p>\n";
echo "\n";
echo "        <p id=\"timelineOfPhotos\">Photographic Timeline Of The Computer Evolution</p>\n";
echo "        <img id=\"newGamingComputerLeft\" src=\"/Photos/corsairComputer.png\" alt=\"New Gaming Computer\">\n";
echo "        <img id=\"newGamingComputerRight\" src=\"/Photos/corsairComputer.png\" alt=\"New Gaming Computer\">\n";
echo "\n";
echo "        <img id=\"downArrow\" src=\"Photos/downArrow.png\" alt=\"Down Arrow\">\n";
echo "\n";
echo "        <img class=\"timeline\" id=\"oneTimeline\" src=\"Photos/oneTimeline.jpg\" alt=\"First Generation Computer\">\n";
echo "        <img class=\"timeline\" id=\"secondTimeline\" src=\"Photos/secondTimeline.png\" alt=\"Second Generation Computer\">\n";
echo "        <img class=\"timeline\" id=\"thirdTimeline\" src=\"Photos/thirdTimeline.jpg\" alt=\"Third Generation Computer\">\n";
echo "        <img class=\"timeline\" id=\"fourthTimeline\" src=\"Photos/fourthTimeline.jpg\" alt=\"Fourth Generation Computer\">\n";
echo "        <img class=\"arrow\" id=\"arrowToRight1\" src=\"Photos/arrowToRight.svg\" alt=\"Arrow To Right\">\n";
echo "        <img class=\"arrow\" id=\"arrowToRight2\" src=\"Photos/arrowToRight.svg\" alt=\"Arrow To Right\">\n";
echo "        <img class=\"arrow\" id=\"arrowToRight3\" src=\"Photos/arrowToRight.svg\" alt=\"Arrow To Right\">\n";
echo "        \n";
echo "        <script src=\"jquery-3.2.1.min.js\"></script>\n";
echo "        <script src=\"theWorks.js\"></script>\n";
echo "        \n";
echo "    </body>\n";
echo "</html>\n";
echo "\n";
echo "\n";
echo "\n";

?>
